package edu.gmu.rcasstev.week08;

public class ObjectWithEquals {
	private int x;

	private double y;

	public ObjectWithEquals(int x, double y) {
		this.x = x;
		this.y = y;
	}

	public void setX(int x) {
		this.x = x;
	}

	/**
	 * The hashCode and equals methods were generated by Eclipse by right
	 * clicking on the class -> Source -> generate hashCode and equals methods.
	 * 
	 */

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + x;
		long temp;
		temp = Double.doubleToLongBits(y);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ObjectWithEquals other = (ObjectWithEquals) obj;
		if (x != other.x)
			return false;
		if (Double.doubleToLongBits(y) != Double.doubleToLongBits(other.y))
			return false;
		return true;
	}
}
